services:

  fuseki:
    image: stain/jena-fuseki:jena4
    ports:
      - "3030:3030"
    volumes:
      - ./data/fuseki:/fuseki
    environment:
      - ADMIN_PASSWORD=fuseki
      - FUSEKI_DATASET_1=resources

  postgres:
    image: postgres:14.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
